apiVersion: apps/v1
kind: Deployment
metadata:
  name: monika_app
spec:
  selector:
    matchLabels:
      app: git-ops-app
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: fessywonder/golang:1.0
        ports:
        - containerPort: 8080
